"""initial_schema

Revision ID: 3cdc35b3c310
Revises: 
Create Date: 2026-07-28 16:31:37.513878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3cdc35b3c310'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('catalog_type', sa.String(length=20), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("catalog_type IN ('categoria', 'cuenta')", name=op.f('ck_catalog_cache_ck_catalog_cache_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalog_cache')),
    sa.UniqueConstraint('catalog_type', 'code', name='uq_catalog_cache_type_code')
    )
    op.create_index('ix_catalog_cache_type_active', 'catalog_cache', ['catalog_type', 'is_active'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_change_required', sa.Boolean(), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'standard')", name=op.f('ck_users_ck_users_role')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('expense_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('image_hash', sa.String(length=64), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('ticket_description', sa.Text(), nullable=True),
    sa.Column('bank', sa.String(length=100), nullable=True),
    sa.Column('transaction_type', sa.String(length=20), nullable=True),
    sa.Column('confidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('group_code', sa.String(length=50), nullable=True),
    sa.Column('consecutive', sa.Integer(), nullable=True),
    sa.Column('final_description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=True),
    sa.Column('sheet_row', sa.Integer(), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('DETECTADO','ESPERANDO_ARCHIVO_ESTABLE','EN_COLA','ANALIZANDO','LISTO_PARA_REVISION','REQUIERE_REVISION','PENDIENTE_DE_ENVIO','ENVIANDO','ENVIADO','ACTUALIZANDO','ACTUALIZADO','DUPLICADO_EXACTO','DUPLICADO_PROBABLE','ERROR_PROCESAMIENTO','ERROR_SHEETS')", name=op.f('ck_expense_records_ck_expense_records_status')),
    sa.CheckConstraint("transaction_type IS NULL OR transaction_type IN ('Transferencia', 'Credito')", name=op.f('ck_expense_records_ck_expense_records_transaction_type')),
    sa.ForeignKeyConstraint(['account_id'], ['catalog_cache.id'], name=op.f('fk_expense_records_account_id_catalog_cache'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['catalog_cache.id'], name=op.f('fk_expense_records_category_id_catalog_cache'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_expense_records_owner_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_records'))
    )
    op.create_index('ix_expense_records_group_consecutive', 'expense_records', ['group_code', 'consecutive'], unique=True, postgresql_where=sa.text('group_code IS NOT NULL AND consecutive IS NOT NULL'))
    op.create_index(op.f('ix_expense_records_image_hash'), 'expense_records', ['image_hash'], unique=True)
    op.create_index(op.f('ix_expense_records_status'), 'expense_records', ['status'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_system_settings_updated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_system_settings'))
    )
    op.create_index(op.f('ix_system_settings_key'), 'system_settings', ['key'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('old_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['record_id'], ['expense_records.id'], name=op.f('fk_audit_events_record_id_expense_records'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index(op.f('ix_audit_events_actor_id'), 'audit_events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_events_record_id'), 'audit_events', ['record_id'], unique=False)
    op.create_table('extraction_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_valid_json', sa.Boolean(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['expense_records.id'], name=op.f('fk_extraction_runs_record_id_expense_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_runs'))
    )
    op.create_index(op.f('ix_extraction_runs_record_id'), 'extraction_runs', ['record_id'], unique=False)
    op.create_table('image_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('original_path', sa.String(length=1000), nullable=False),
    sa.Column('optimized_path', sa.String(length=1000), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('exif_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('owner_folder', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("owner_folder IN ('Ruben', 'Esme')", name=op.f('ck_image_files_ck_image_files_owner_folder')),
    sa.ForeignKeyConstraint(['record_id'], ['expense_records.id'], name=op.f('fk_image_files_record_id_expense_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_image_files')),
    sa.UniqueConstraint('record_id', name=op.f('uq_image_files_record_id'))
    )
    op.create_index(op.f('ix_image_files_owner_folder'), 'image_files', ['owner_folder'], unique=False)
    op.create_index(op.f('ix_image_files_sha256_hash'), 'image_files', ['sha256_hash'], unique=True)
    op.create_table('processing_queue',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('enqueued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('worker_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('EN_COLA', 'ANALIZANDO', 'COMPLETADO', 'ERROR_PERMANENTE')", name=op.f('ck_processing_queue_ck_processing_queue_status')),
    sa.ForeignKeyConstraint(['record_id'], ['expense_records.id'], name=op.f('fk_processing_queue_record_id_expense_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_queue')),
    sa.UniqueConstraint('record_id', name=op.f('uq_processing_queue_record_id'))
    )
    op.create_index('ix_processing_queue_fifo', 'processing_queue', ['status', 'enqueued_at', 'id'], unique=False)
    op.create_table('sheet_sync',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('sheet_name', sa.String(length=100), nullable=False),
    sa.Column('sheet_row', sa.Integer(), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.CheckConstraint("sync_status IN ('inserted', 'updated', 'deleted', 'error')", name=op.f('ck_sheet_sync_ck_sheet_sync_status')),
    sa.ForeignKeyConstraint(['record_id'], ['expense_records.id'], name=op.f('fk_sheet_sync_record_id_expense_records'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sheet_sync')),
    sa.UniqueConstraint('record_id', name=op.f('uq_sheet_sync_record_id'))
    )
    op.create_index('ix_sheet_sync_name_row', 'sheet_sync', ['sheet_name', 'sheet_row'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sheet_sync_name_row', table_name='sheet_sync')
    op.drop_table('sheet_sync')
    op.drop_index('ix_processing_queue_fifo', table_name='processing_queue')
    op.drop_table('processing_queue')
    op.drop_index(op.f('ix_image_files_sha256_hash'), table_name='image_files')
    op.drop_index(op.f('ix_image_files_owner_folder'), table_name='image_files')
    op.drop_table('image_files')
    op.drop_index(op.f('ix_extraction_runs_record_id'), table_name='extraction_runs')
    op.drop_table('extraction_runs')
    op.drop_index(op.f('ix_audit_events_record_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_system_settings_key'), table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_expense_records_status'), table_name='expense_records')
    op.drop_index(op.f('ix_expense_records_image_hash'), table_name='expense_records')
    op.drop_index('ix_expense_records_group_consecutive', table_name='expense_records', postgresql_where=sa.text('group_code IS NOT NULL AND consecutive IS NOT NULL'))
    op.drop_table('expense_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_catalog_cache_type_active', table_name='catalog_cache')
    op.drop_table('catalog_cache')
    # ### end Alembic commands ###
